title: MethylScoreAML
author: Marchi et al., 2023. Lamba Lab @ University of Florida. Please do not share this notebook publicly.
copyright: "2023"  # Copyright year to be placed in the footer
# logo: "_logos/dna1.gif"
exclude_patterns: [.venv,.venv_py37,.venv_py38, .venv_data_vizualization, .venv_pacmap, .venv_sklearn,
                  Code_past, Benchmarking, .past_code_files]
only_build_toc_files: true

# Short description about the book
description: >-
  This is Francisco Marchi's electronic notebook, which belongs to Lamba Lab at UF.

execute:
  execute_notebooks: "off"
  exclude_patterns: [.venv,.venv_py38, .venv_data_vizualization, .venv_pacmap, .venv_sklearn,
                    Code_past, Benchmarking, .past_code_files]
# HTML-specific settings
html:
  home_page_in_navbar: false

# Interact link settings
notebook_interface: "notebook"

# Launch button settings
#repository:
#  url: https://github.com/executablebooks/quantecon-mini-example
#  path_to_book: "book"

# LaTeX settings
# bibtex_bibfiles:
#   - _bibliography/references.bib
# latex:
#   latex_engine: "xelatex"
#   latex_documents:
#     targetname: book.tex

html:
  comments:
    hypothesis: False
